name: mongo-kafka
lang: java
lang_version: "17"
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  branches:
    - master
    - /^\d+\.\d+\.x$/
  promotions:
    - name: Create Tag
      pipeline_file: .semaphore/create-tag.yml
      auto_promote_when: "result = 'passed' and branch =~ '^\\d+\\.\\d+\\.x$'"
  tasks:
    - name: create-mongo-kafka-tag
      branch: master
      pipeline_file: .semaphore/create-tag.yml
      parameters:
        - name: BRANCH_NAME
          required: true
          description: 'Branch used to create a tag for CP-patched branches (for example 2.0.x, 1.14.x). Not intended for hotfix branches.'
